local crdsonnet = import 'github.com/crdsonnet/crdsonnet/crdsonnet/main.libsonnet';
function(schema, refSource)
  // Keep generator snippets readable while emitting valid docsonnet metadata keys.
  local documentedRefSource = std.strReplace(refSource, 'function:', "'function':");
  local defsKey = if '$defs' in schema then '$defs' else 'definitions';
  local processor = crdsonnet.processor.new('ast') + {
    renderEngine+: {
      engine+: {
        // CRDsonnet emits invalid identifiers for $self and $ref.
        // Preserve JSON keys; only use Dollar in helper function names.
        functionName(name):: super.functionName(std.strReplace(name, '$', 'dollar-')),
      },
    },
  };

  // ponytail: break the known recursive encoding/Schema/items references into
  // object setters. Use separate builders for their values; add cycle-aware
  // reference rendering if new schemas need other recursive definitions.
  // The source schema remains unchanged for validation.
  local forGeneration(value) =
    if std.isArray(value) then [forGeneration(v) for v in value]
    else if std.isObject(value) then
      if std.isString(std.get(value, '$ref', null)) && std.member([
        '#/$defs/encoding',
        '#/definitions/Schema',
        '#/definitions/schema',
        '#/definitions/primitivesItems',
      ], value['$ref']) then { type: 'object' }
      else {
        [k]:
          if k == 'properties' then {
            // CRDsonnet's parser adds metadata to property schemas, so it needs
            // objects. Its renderer understands its internal { type: boolean }.
            [p]: if std.isBoolean(value[k][p]) then { type: value[k][p] }
            else forGeneration(value[k][p])
            for p in std.objectFields(value[k])
          }
          else forGeneration(value[k])
        for k in std.objectFields(value)
      }
    else value;

  local definitions = forGeneration(schema[defsKey]);

  '// Generated by generate.jsonnet; do not edit.\n' +
  crdsonnet.schema.render('openapi', forGeneration(schema), processor).toString() +
  '\n+ { definitions: ' + std.join('\n+\n', [
    crdsonnet.schema.render(name, definitions[name] + { [defsKey]: definitions }, processor).toString()
    for name in std.objectFields(definitions)
  ]) + '\n}\n' + documentedRefSource
